enum Token_Type {
  LEFT_PARAM, RIGHT_PARAM, LEFT_BRACE, RIGHT_BRACE, COMMA, 
  DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,

  BANG, BANG_EQUAL, 
  EQUAL, EQUAL_EQUAL, 
  GREATER_THAN, GREATER_THAN_EQUAL,
  LESS_THAN, LESS_THAN_EQUAL,

  IDENITFIER, STRING, NUMBER,
  
  AND, CLASS, ELSE, FALSE, FUN, FOR, IF, NIL, OR,
  PRINT, RETURN, SUPER, THIS, TRUE, VAR, WHILE,

  EOF,
  
  // delete after testing
  PLACEHOLDER
};
